# -*- coding: utf-8 -*-
"""healthcare 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h88dGQl8UZPQl_r9ktr6LnZggI1Hp-vO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


pd.set_option('display.max_columns', None)

file_path = "/content/healthcare_dataset.csv.xls"

df = pd.read_csv(file_path)

print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

df['Date of Admission'] = pd.to_datetime(
    df['Date of Admission'], errors='coerce'
)

df['Discharge Date'] = pd.to_datetime(
    df['Discharge Date'], errors='coerce'
)


df['Billing Amount'] = pd.to_numeric(
    df['Billing Amount'], errors='coerce'
)

df['Stay Duration'] = (
    df['Discharge Date'] - df['Date of Admission']
).dt.days

df = df[df['Stay Duration'] >= 0]


df = df.dropna(
    subset=[
        'Medical Condition',
        'Insurance Provider',
        'Billing Amount',
        'Date of Admission'
    ]
)

print("\nCleaned Dataset Shape:", df.shape)

condition_insurance = pd.crosstab(
    df['Medical Condition'],
    df['Insurance Provider']
)

condition_insurance.plot(
    kind='bar',
    stacked=True,
    figsize=(12,6)
)

plt.title('Patients by Medical Condition and Insurance Provider')
plt.xlabel('Medical Condition')
plt.ylabel('Number of Patients')
plt.xticks(rotation=45)
plt.legend(title='Insurance Provider')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))

sns.violinplot(
    data=df,
    x='Medical Condition',
    y='Billing Amount'
)

plt.title('Billing Amount Distribution by Medical Condition')
plt.xlabel('Medical Condition')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))

sns.violinplot(
    data=df,
    x='Insurance Provider',
    y='Billing Amount'
)

plt.title('Billing Amount Distribution by Insurance Provider')
plt.xlabel('Insurance Provider')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

monthly_admissions = (
    df.set_index('Date of Admission')
      .resample('M')
      .size()
)

plt.figure(figsize=(14,6))

plt.plot(
    monthly_admissions.index,
    monthly_admissions.values,
    marker='o'
)

plt.title('Monthly Patient Admissions')
plt.xlabel('Date')
plt.ylabel('Number of Admissions')
plt.grid(True)
plt.tight_layout()
plt.show()

yearly_admissions = (
    df['Date of Admission']
    .dt.year
    .value_counts()
    .sort_index()
)

plt.figure(figsize=(10,5))

plt.plot(
    yearly_admissions.index,
    yearly_admissions.values,
    marker='o'
)

plt.title('Yearly Patient Admissions')
plt.xlabel('Year')
plt.ylabel('Number of Admissions')
plt.grid(True)
plt.tight_layout()
plt.show()

correlation_data = df[
    ['Age', 'Stay Duration', 'Billing Amount']
]

correlation_matrix = correlation_data.corr()

print("\nCorrelation Matrix:")
print(correlation_matrix)

plt.figure(figsize=(7,5))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title('Correlation Matrix')
plt.tight_layout()
plt.show()

print("\nBilling Amount Statistics:")
print(df['Billing Amount'].describe())

print("\nStay Duration Statistics:")
print(df['Stay Duration'].describe())

print("\nAge Statistics:")
print(df['Age'].describe())

condition_cost = (
    df.groupby('Medical Condition')['Billing Amount']
      .agg(['mean', 'median', 'count'])
      .sort_values('mean', ascending=False)
)

print("\nBilling Summary by Medical Condition:")
print(condition_cost)

insurance_cost = (
    df.groupby('Insurance Provider')['Billing Amount']
      .agg(['mean', 'median', 'count'])
      .sort_values('mean', ascending=False)
)

print("\nBilling Summary by Insurance Provider:")
print(insurance_cost)

stay_summary = (
    df.groupby('Medical Condition')['Stay Duration']
      .agg(['mean', 'median'])
      .sort_values('mean', ascending=False)
)

print("\nStay Duration by Medical Condition:")
print(stay_summary)

correlation = correlation_data.corr()

print(correlation)

plt.figure(figsize=(7,5))

sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title('Correlation Matrix')
plt.show()

print(df['Billing Amount'].describe())

condition_cost = df.groupby(
    'Medical Condition'
)['Billing Amount'].mean()

print(condition_cost)

insurance_cost = df.groupby(
    'Insurance Provider'
)['Billing Amount'].mean()

print(insurance_cost)

stay = df.groupby(
    'Medical Condition'
)['Stay Duration'].mean()

print(stay)

print("EXECUTIVE SUMMARY")
print("------------------")

print("Total Patients:", len(df))

print(
    "Average Billing Amount:",
    round(df['Billing Amount'].mean(), 2)
)

print(
    "Average Stay Duration:",
    round(df['Stay Duration'].mean(), 2),
    "days"
)

print(
    "Average Patient Age:",
    round(df['Age'].mean(), 2)
)

print("\nHEALTHCARE MANAGEMENT RECOMMENDATIONS")
print("--------------------------------------")

print("1. Monitor high-cost medical conditions.")
print("2. Analyze insurance-wise billing patterns.")
print("3. Prepare resources during admission surges.")
print("4. Monitor patients with long hospital stays.")
print("5. Use admission trends for staff planning.")
print("6. Use billing analysis for better budget planning.")