# -*- coding: utf-8 -*-
"""AAPL 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H1JCGkSHZO4D6zIqfPP2OVTs3FhESUjd
"""

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

df = pd.read_excel('AAPL.xlsx')

df.columns = df.columns.str.strip()
df['Date'] = pd.to_datetime(df['Date'])
cols = ['Open', 'High', 'Low', 'Close', 'Volume']
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df.dropna(subset=cols, inplace=True)

df['Price_Delta'] = df['Close'] - df['Open']

df['Daily_Return'] = df['Close'].pct_change() * 100

df['Volume_MA'] = df['Volume'].rolling(20).mean()

Q1 = df['Volume'].quantile(0.25)
Q3 = df['Volume'].quantile(0.75)
IQR = Q3 - Q1

anomalies = df[
    (df['Volume'] < Q1 - 1.5 * IQR) |
    (df['Volume'] > Q3 + 1.5 * IQR)
]

Q1 = df['Volume'].quantile(0.25)
Q3 = df['Volume'].quantile(0.75)
IQR = Q3 - Q1

anomalies = df[
    (df['Volume'] < Q1 - 1.5 * IQR) |
    (df['Volume'] > Q3 + 1.5 * IQR)
]


returns = df['Daily_Return'].dropna()

print("Mean Return:", returns.mean())
print("Variance:", returns.var())
print("Standard Deviation:", returns.std())

print("\nAnomalous Trading Days:")
print(anomalies[['Date', 'Volume']])

plt.figure(figsize=(10,4))
plt.plot(df['Date'], df['Volume'], label='Volume')
plt.plot(df['Date'], df['Volume_MA'], label='20-Day Average')
plt.title("Shopify Trading Volume Trend")
plt.xlabel("Date")
plt.ylabel("Volume")
plt.legend()
plt.show()

plt.figure(figsize=(8,4))
plt.hist(returns, bins=30)
plt.title("Shopify Daily Return Distribution")
plt.xlabel("Daily Return (%)")
plt.ylabel("Frequency")
plt.show()

# Display final data
df.head()