# -*- coding: utf-8 -*-
"""healthcare 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1neUn9QHmt6gV7CTh6CSD-Mt_zo3MaT0a
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/healthcare_dataset.csv.xls')

print("Dataset Shape:", df.shape)
print("\nColumn Names:")
print(df.columns)

print("\nFirst 5 Records:")
display(df.head())

print("\nMissing Values:")
print(df.isnull().sum())

categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    df[col] = df[col].fillna('Unknown')


df['Billing Amount'] = df['Billing Amount'].fillna(
    df['Billing Amount'].median()
)

df['Date of Admission'] = pd.to_datetime(
    df['Date of Admission'], errors='coerce'
)

df['Discharge Date'] = pd.to_datetime(
    df['Discharge Date'], errors='coerce'
)

df['Date of Admission'] = df['Date of Admission'].ffill()
df['Discharge Date'] = df['Discharge Date'].ffill()

df['Hospital Stay Days'] = (
    df['Discharge Date'] - df['Date of Admission']
).dt.days

print("\nHospital Stay Statistics:")
print(df['Hospital Stay Days'].describe())

df['Admission Type'] = df['Admission Type'].str.strip().str.title()

# Keep only required admission categories
df['Urgency Category'] = df['Admission Type'].replace({
    'Emergency': 'Emergency',
    'Urgent': 'Urgent',
    'Elective': 'Elective'
})

print("\nAdmission Categories:")
print(df['Urgency Category'].value_counts())

print("\nBilling Amount Statistics:")
print(df['Billing Amount'].describe())

# Mean, Median and Standard Deviation
print("\nMean Billing Amount:",
      df['Billing Amount'].mean())

print("Median Billing Amount:",
      df['Billing Amount'].median())

print("Standard Deviation:",
      df['Billing Amount'].std())

demographics = df.groupby('Medical Condition').agg(
    Patients=('Name', 'count'),
    Average_Age=('Age', 'mean'),
    Male=('Gender', lambda x: (x == 'Male').sum()),
    Female=('Gender', lambda x: (x == 'Female').sum()),
    Average_Billing=('Billing Amount', 'mean'),
    Average_Stay=('Hospital Stay Days', 'mean')
)

print("\nDemographics by Medical Condition:")
display(demographics)

condition_count = df['Medical Condition'].value_counts()

print("\nPatients by Medical Condition:")
print(condition_count)

plt.figure(figsize=(10,5))
condition_count.plot(kind='bar')
plt.title('Patients by Medical Condition')
plt.xlabel('Medical Condition')
plt.ylabel('Number of Patients')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(7,5))
df['Urgency Category'].value_counts().plot(kind='bar')
plt.title('Admission by Urgency')
plt.xlabel('Urgency')
plt.ylabel('Number of Patients')
plt.xticks(rotation=0)
plt.show()

plt.figure(figsize=(8,5))
plt.hist(df['Billing Amount'], bins=30)
plt.title('Billing Amount Distribution')
plt.xlabel('Billing Amount')
plt.ylabel('Number of Patients')
plt.show()

plt.figure(figsize=(8,5))
plt.hist(df['Hospital Stay Days'], bins=20)
plt.title('Hospital Stay Distribution')
plt.xlabel('Stay Days')
plt.ylabel('Number of Patients')
plt.show()

print("\nFinal Dataset:")
display(df.head())

print("\nFinal Shape:", df.shape)













