# -*- coding: utf-8 -*-
"""student perform 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgGIPyk_anupYjwvpI7t0J8ky7Pgj6Wz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/StudentsPerformance.csv.xls')

print("Dataset loaded successfully!")
print(df.head())

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print(df.isnull().sum())


cat_cols = [
    'gender',
    'race/ethnicity',
    'parental level of education',
    'lunch',
    'test preparation course'
]

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Missing values handled!")

for col in cat_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

print(df[cat_cols].head())

for col in cat_cols:
    print("\n", col)
    print(df[col].value_counts())

score_cols = [
    'math score',
    'reading score',
    'writing score'
]

quartiles = df[score_cols].quantile([0.25, 0.50, 0.75])

print(quartiles)

df['total marks'] = (
    df['math score'] +
    df['reading score'] +
    df['writing score']
)

print(df[['math score', 'reading score', 'writing score', 'total marks']].head())

df['percentage'] = (df['total marks'] / 300) * 100

print(df[['total marks', 'percentage']].head())

df['percentage'] = df['percentage'].round(2)

print(df[['total marks', 'percentage']].head())

def find_outliers(column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower) |
        (df[column] > upper)
    ]

    return outliers, lower, upper

math_outliers, lower, upper = find_outliers('math score')

print("Math Score")
print("Lower Limit:", lower)
print("Upper Limit:", upper)
print("Number of Outliers:", len(math_outliers))

reading_outliers, lower, upper = find_outliers('reading score')

print("Reading Score")
print("Lower Limit:", lower)
print("Upper Limit:", upper)
print("Number of Outliers:", len(reading_outliers))

writing_outliers, lower, upper = find_outliers('writing score')

print("Writing Score")
print("Lower Limit:", lower)
print("Upper Limit:", upper)
print("Number of Outliers:", len(writing_outliers))

df['outlier'] = False

for col in score_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df['outlier'] = df['outlier'] | (
        (df[col] < lower) | (df[col] > upper)
    )

print(df['outlier'].value_counts())

outlier_students = df[df['outlier'] == True]

print(outlier_students[
    ['gender',
     'race/ethnicity',
     'math score',
     'reading score',
     'writing score',
     'total marks',
     'percentage']
])

plt.figure(figsize=(10, 5))

sns.boxplot(data=df[score_cols])

plt.title("Student Subject Score Outliers")
plt.ylabel("Score")
plt.show()

print(df.head())
print("\nFinal Shape:", df.shape)

df.to_csv('StudentsPerformance_cleaned.csv', index=False)

print("Cleaned dataset saved successfully!")