# -*- coding: utf-8 -*-
"""AAPL 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDLujN1ZzS03dh08xxB2zSDcgm4EF9RJ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns



df = pd.read_excel("/content/AAPL.xlsx")

df.columns = df.columns.str.strip()

cols = ["Open", "High", "Low", "Close", "Volume"]

for col in cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df.dropna(subset=cols)
df = df.drop_duplicates()

if "Date" in df.columns:
    df["Date"] = pd.to_datetime(df["Date"])
    df = df.sort_values("Date")

df["Daily_Return"] = (
    (df["Close"] - df["Open"]) / df["Open"]
) * 100

x = df["Date"] if "Date" in df.columns else df.index

plt.figure(figsize=(12, 6))

plt.plot(x, df["Open"], label="Open")
plt.plot(x, df["High"], label="High")
plt.plot(x, df["Low"], label="Low")
plt.plot(x, df["Close"], label="Close")

plt.title("OHLC Prices Over Time")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 5))

plt.plot(x, df["Volume"], label="Trading Volume")

plt.title("Trading Volume Over Time")
plt.xlabel("Date")
plt.ylabel("Volume")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

df["MA_20"] = df["Close"].rolling(20).mean()
df["MA_50"] = df["Close"].rolling(50).mean()

plt.figure(figsize=(12, 6))

plt.plot(x, df["Close"], label="Daily Close")
plt.plot(x, df["MA_20"], label="20-Day Moving Average")
plt.plot(x, df["MA_50"], label="50-Day Moving Average")

plt.title("Closing Price with Moving Averages")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))

sns.histplot(
    df["Daily_Return"],
    bins=30,
    kde=True
)

plt.title("Daily Return Distribution")
plt.xlabel("Daily Return (%)")
plt.ylabel("Frequency")
plt.grid(True)
plt.tight_layout()
plt.show()

mean_return = df["Daily_Return"].mean()
variance_return = df["Daily_Return"].var()
std_return = df["Daily_Return"].std()

high_volatility = df[
    abs(df["Daily_Return"]) > 2 * std_return
]

print("\nReturn Statistics")
print("--------------------------------")
print("Mean Return          :", round(mean_return, 4), "%")
print("Variance             :", round(variance_return, 4))
print("Standard Deviation   :", round(std_return, 4), "%")

print("\nPrice Statistics")
print("--------------------------------")
print("Highest Closing Price:", df["Close"].max())
print("Lowest Closing Price :", df["Close"].min())

print("\nTrading Volume")
print("--------------------------------")
print("Average Volume       :", round(df["Volume"].mean(), 2))
print("Maximum Volume       :", df["Volume"].max())

print("\nHigh-Volatility Days")
print("--------------------------------")
print("Number of Days       :", len(high_volatility))

if len(high_volatility) > 0:
    print("\nHigh-Volatility Records:")
    print(
        high_volatility[
            ["Open", "Close", "Daily_Return", "Volume"]
        ]
    )

if std_return < 2:
    print("Stock Stability: Relatively stable returns.")
else:
    print("Stock Stability: Higher variation in daily returns.")

print(
    "High-volatility periods are identified using "
    "daily returns beyond ±2 standard deviations."
)

